#!/bin/sh
#
# @name baby_k aka leonardo_2 from prismalab@unina
#
# @type tilting H octarotor coaxial
#
# @maintainer Alessandro De Crescenzo <ale-dc@live.it>
#

. ${R}etc/init.d/rc.mc_defaults


param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 8

param set-default CA_ROTOR0_PX 0.185 #M1 CCW
param set-default CA_ROTOR0_PY 0.180
param set-default CA_ROTOR0_PZ 0.0135
param set-default CA_ROTOR0_KM 0.05
param set-default CA_ROTOR1_PX 0.185 #M2 CW
param set-default CA_ROTOR1_PY -0.180
param set-default CA_ROTOR1_PZ 0.0135
param set-default CA_ROTOR1_KM -0.05
param set-default CA_ROTOR2_PX -0.185  #M3 CCW
param set-default CA_ROTOR2_PY -0.180
param set-default CA_ROTOR2_PZ 0.0135
param set-default CA_ROTOR2_KM 0.05
param set-default CA_ROTOR3_PX -0.185 #M4 CW
param set-default CA_ROTOR3_PY 0.180
param set-default CA_ROTOR3_PZ 0.0135
param set-default CA_ROTOR3_KM -0.05

param set-default CA_ROTOR4_PX 0.185 #M5 CCW
param set-default CA_ROTOR4_PY -0.180
param set-default CA_ROTOR4_PZ -0.0685
param set-default CA_ROTOR4_KM 0.05
param set-default CA_ROTOR5_PX 0.185 #M6 CW
param set-default CA_ROTOR5_PY 0.180
param set-default CA_ROTOR5_PZ -0.0685
param set-default CA_ROTOR5_KM -0.05
param set-default CA_ROTOR6_PX -0.185  #M7 CCW
param set-default CA_ROTOR6_PY 0.180
param set-default CA_ROTOR6_PZ -0.0685
param set-default CA_ROTOR6_KM 0.05
param set-default CA_ROTOR7_PX -0.185 #M8 CW
param set-default CA_ROTOR7_PY -0.180
param set-default CA_ROTOR7_PZ -0.0685
param set-default CA_ROTOR7_KM -0.05

param set-default PWM_MAIN_FUNC1 101 #esc
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
param set-default PWM_MAIN_FUNC5 105
param set-default PWM_MAIN_FUNC6 106
param set-default PWM_MAIN_FUNC7 107
param set-default PWM_MAIN_FUNC8 108
param set-default PWM_MAIN_FUNC9 201 #servo
param set-default PWM_MAIN_FUNC10 202
param set-default PWM_MAIN_FUNC11 203
param set-default PWM_MAIN_FUNC12 204


